# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w1.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 151, 161))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_ord_num = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_ord_num.setGeometry(QtCore.QRect(110, 60, 31, 25))
        self.lineEdit_ord_num.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_ord_num.setObjectName("lineEdit_ord_num")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_grp_num = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_grp_num.setGeometry(QtCore.QRect(110, 30, 31, 25))
        self.lineEdit_grp_num.setText("")
        self.lineEdit_grp_num.setObjectName("lineEdit_grp_num")
        self.pushButton_var_clc = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_var_clc.setGeometry(QtCore.QRect(10, 120, 131, 25))
        self.pushButton_var_clc.setObjectName("pushButton_var_clc")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(110, 90, 31, 17))
        self.label_9.setObjectName("label_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 10, 631, 521))
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_b = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_b.setGeometry(QtCore.QRect(220, 370, 41, 23))
        self.radioButton_b.setObjectName("radioButton_b")
        self.radioButton_a = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_a.setGeometry(QtCore.QRect(220, 340, 41, 23))
        self.radioButton_a.setObjectName("radioButton_a")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 30, 311, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidget_set_a = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_set_a.setGeometry(QtCore.QRect(30, 30, 171, 211))
        self.listWidget_set_a.setObjectName("listWidget_set_a")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 16, 17))
        self.label_4.setObjectName("label_4")
        self.listWidget_set_b = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_set_b.setGeometry(QtCore.QRect(30, 260, 171, 211))
        self.listWidget_set_b.setObjectName("listWidget_set_b")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 340, 16, 17))
        self.label_5.setObjectName("label_5")
        self.pushButton_clear_a = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_clear_a.setGeometry(QtCore.QRect(210, 110, 89, 25))
        self.pushButton_clear_a.setObjectName("pushButton_clear_a")
        self.pushButton_save_a = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save_a.setGeometry(QtCore.QRect(210, 80, 89, 25))
        self.pushButton_save_a.setObjectName("pushButton_save_a")
        self.pushButton_clear_b = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_clear_b.setGeometry(QtCore.QRect(210, 340, 89, 25))
        self.pushButton_clear_b.setToolTip("")
        self.pushButton_clear_b.setObjectName("pushButton_clear_b")
        self.pushButton_save_b = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save_b.setGeometry(QtCore.QRect(210, 310, 89, 25))
        self.pushButton_save_b.setObjectName("pushButton_save_b")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(0, 235, 391, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_read_a = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_read_a.setGeometry(QtCore.QRect(210, 50, 89, 25))
        self.pushButton_read_a.setObjectName("pushButton_read_a")
        self.pushButton_read_b = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_read_b.setGeometry(QtCore.QRect(210, 280, 89, 25))
        self.pushButton_read_b.setObjectName("pushButton_read_b")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 30, 191, 481))
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidget_men_names = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_men_names.setGeometry(QtCore.QRect(10, 30, 171, 211))
        self.listWidget_men_names.setDragEnabled(False)
        self.listWidget_men_names.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget_men_names.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_men_names.setObjectName("listWidget_men_names")
        self.listWidget_women_names = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_women_names.setGeometry(QtCore.QRect(10, 260, 171, 211))
        self.listWidget_women_names.setDragEnabled(False)
        self.listWidget_women_names.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget_women_names.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_women_names.setObjectName("listWidget_women_names")
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setGeometry(QtCore.QRect(0, 240, 281, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_cpy = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_cpy.setGeometry(QtCore.QRect(210, 240, 89, 81))
        self.pushButton_cpy.setAutoDefault(False)
        self.pushButton_cpy.setDefault(False)
        self.pushButton_cpy.setFlat(False)
        self.pushButton_cpy.setObjectName("pushButton_cpy")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 180, 161, 321))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 121, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_mtr_s = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mtr_s.setObjectName("pushButton_mtr_s")
        self.verticalLayout.addWidget(self.pushButton_mtr_s)
        self.pushButton_mtr_r = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mtr_r.setObjectName("pushButton_mtr_r")
        self.verticalLayout.addWidget(self.pushButton_mtr_r)
        self.pushButton_mtr_rus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mtr_rus.setObjectName("pushButton_mtr_rus")
        self.verticalLayout.addWidget(self.pushButton_mtr_rus)
        self.pushButton_mtr_rds = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mtr_rds.setObjectName("pushButton_mtr_rds")
        self.verticalLayout.addWidget(self.pushButton_mtr_rds)
        self.pushButton_mtr_rms = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mtr_rms.setObjectName("pushButton_mtr_rms")
        self.verticalLayout.addWidget(self.pushButton_mtr_rms)
        self.pushButton_mtr_umr = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mtr_umr.setObjectName("pushButton_mtr_umr")
        self.verticalLayout.addWidget(self.pushButton_mtr_umr)
        self.pushButton_mtr_st = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mtr_st.setObjectName("pushButton_mtr_st")
        self.verticalLayout.addWidget(self.pushButton_mtr_st)
        self.pushButton_abt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_abt.setGeometry(QtCore.QRect(10, 510, 151, 25))
        self.pushButton_abt.setToolTip("")
        self.pushButton_abt.setObjectName("pushButton_abt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStatusTip("")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ДМ - Лаб2"))
        self.groupBox.setTitle(_translate("MainWindow", "Варіант"))
        self.label_3.setStatusTip(_translate("MainWindow", "Номер варіанту"))
        self.label_3.setText(_translate("MainWindow", "Варіант:"))
        self.lineEdit_ord_num.setStatusTip(_translate("MainWindow", "Порядковий номер студента у списку групи"))
        self.label.setText(_translate("MainWindow", "Група ІО-"))
        self.label_2.setText(_translate("MainWindow", "№ у списку:"))
        self.lineEdit_grp_num.setStatusTip(_translate("MainWindow", "Номер групи ІО-ХХ"))
        self.pushButton_var_clc.setStatusTip(_translate("MainWindow", "Розрахувати варіант"))
        self.pushButton_var_clc.setText(_translate("MainWindow", "Розрахувати"))
        self.label_9.setStatusTip(_translate("MainWindow", "Номер варіанту"))
        self.label_9.setText(_translate("MainWindow", "--"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Задавання множин"))
        self.radioButton_b.setStatusTip(_translate("MainWindow", "Скопіювати в множину B"))
        self.radioButton_b.setText(_translate("MainWindow", "B"))
        self.radioButton_a.setStatusTip(_translate("MainWindow", "Скопіювати в множину A"))
        self.radioButton_a.setText(_translate("MainWindow", "A"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Множини"))
        self.listWidget_set_a.setStatusTip(_translate("MainWindow", "Елементи множини A"))
        self.label_4.setText(_translate("MainWindow", "A:"))
        self.listWidget_set_b.setStatusTip(_translate("MainWindow", "Елементи множини B"))
        self.label_5.setText(_translate("MainWindow", "B:"))
        self.pushButton_clear_a.setStatusTip(_translate("MainWindow", "Очистити множину A"))
        self.pushButton_clear_a.setText(_translate("MainWindow", "Очистити"))
        self.pushButton_save_a.setStatusTip(_translate("MainWindow", "Зберегти в файл елементи множини A"))
        self.pushButton_save_a.setText(_translate("MainWindow", "Зберегти"))
        self.pushButton_clear_b.setStatusTip(_translate("MainWindow", "Очистити множину A"))
        self.pushButton_clear_b.setText(_translate("MainWindow", "Очистити"))
        self.pushButton_save_b.setStatusTip(_translate("MainWindow", "Зберегти в файл елементи множини B"))
        self.pushButton_save_b.setText(_translate("MainWindow", "Зберегти"))
        self.pushButton_read_a.setStatusTip(_translate("MainWindow", "Зчитати з файлу елементи множини A"))
        self.pushButton_read_a.setText(_translate("MainWindow", "Зчитати"))
        self.pushButton_read_b.setStatusTip(_translate("MainWindow", "Зчитати з файлу елементи множини B"))
        self.pushButton_read_b.setText(_translate("MainWindow", "Зчитати"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Імена"))
        self.listWidget_men_names.setStatusTip(_translate("MainWindow", "Чоловічі імена"))
        self.listWidget_women_names.setStatusTip(_translate("MainWindow", "Жіночі імена"))
        self.pushButton_cpy.setStatusTip(_translate("MainWindow", "Скопіювати імена в множину"))
        self.pushButton_cpy.setText(_translate("MainWindow", "Copy ->"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Матриці"))
        self.pushButton_mtr_s.setStatusTip(_translate("MainWindow", "Матричне представлення відношення  S"))
        self.pushButton_mtr_s.setText(_translate("MainWindow", "S"))
        self.pushButton_mtr_r.setStatusTip(_translate("MainWindow", "Матричне представлення відношення R"))
        self.pushButton_mtr_r.setText(_translate("MainWindow", "R"))
        self.pushButton_mtr_rus.setStatusTip(_translate("MainWindow", "Матричне представлення відношення R S"))
        self.pushButton_mtr_rus.setText(_translate("MainWindow", "R ⋃ S"))
        self.pushButton_mtr_rds.setStatusTip(_translate("MainWindow", "Матричне представлення відношення R S"))
        self.pushButton_mtr_rds.setText(_translate("MainWindow", "R ⋂ S"))
        self.pushButton_mtr_rms.setStatusTip(_translate("MainWindow", "Матричне представлення відношення R\\S"))
        self.pushButton_mtr_rms.setText(_translate("MainWindow", "R \\ S"))
        self.pushButton_mtr_umr.setStatusTip(_translate("MainWindow", "Матричне представлення відношення U \\ R"))
        self.pushButton_mtr_umr.setText(_translate("MainWindow", "U \\ R"))
        self.pushButton_mtr_st.setStatusTip(_translate("MainWindow", "Матричне представлення відношення S^(-1)"))
        self.pushButton_mtr_st.setText(_translate("MainWindow", "S^( -1)"))
        self.pushButton_abt.setStatusTip(_translate("MainWindow", "Інформація про програму"))
        self.pushButton_abt.setText(_translate("MainWindow", "Про програму"))


